export const coinsData = [
    { id: 1, name: "Bitcoin", symbol: "BTC" },
    { id: 1027, name: "Ethereum", symbol: "ETH" },
    { id: 825, name: "Tether", symbol: "USDT" },
    { id: 74, name: "Dogecoin", symbol: "DOGE" },
    { id: 2010, name: "Cardano", symbol: "ADA" },
    { id: 1839, name: "Binance Coin", symbol: "BNB" },
    { id: 52, name: "XRP", symbol: "XRP" },
    { id: 8916, name: "Internet Computer", symbol: "ICP" },
    { id: 6636, name: "Polkadot", symbol: "DOT" },
    { id: 3408, name: "USD Coin", symbol: "USDC" },
    { id: 1831, name: "Bitcoin Cash", symbol: "BCH" },
    { id: 2, name: "Litecoin", symbol: "LTC" },
    { id: 7083, name: "Uniswap", symbol: "UNI" },
    { id: 4687, name: "Binance USD", symbol: "BUSD" },
    { id: 1975, name: "Chainlink", symbol: "LINK" },
    { id: 512, name: "Stellar", symbol: "XLM" },
    { id: 5426, name: "Solana", symbol: "SOL" },
    { id: 3717, name: "Wrapped Bitcoin", symbol: "WBTC" },
    { id: 1321, name: "Ethereum Classic", symbol: "ETC" },
    { id: 3890, name: "Polygon", symbol: "MATIC" },
    { id: 2416, name: "THETA", symbol: "THETA" },
    { id: 3077, name: "VeChain", symbol: "VET" },
    { id: 2280, name: "Filecoin", symbol: "FIL" },
    { id: 4943, name: "Dai", symbol: "DAI" },
    { id: 1958, name: "TRON", symbol: "TRX" },
    { id: 1765, name: "EOS", symbol: "EOS" },
    { id: 328, name: "Monero", symbol: "XMR" },
    { id: 7278, name: "Aave", symbol: "AAVE" },
    { id: 5994, name: "SHIBA INU", symbol: "SHIB" },
    { id: 1376, name: "Neo", symbol: "NEO" },
    { id: 3602, name: "Bitcoin SV", symbol: "BSV" },
    { id: 4256, name: "Klaytn", symbol: "KLAY" },
    { id: 2011, name: "Tezos", symbol: "XTZ" },
    { id: 3957, name: "UNUS SED LEO", symbol: "LEO" },
    { id: 4195, name: "FTX Token", symbol: "FTT" },
    { id: 4030, name: "Algorand", symbol: "ALGO" },
    { id: 3635, name: "Crypto.com Coin", symbol: "CRO" },
    { id: 1720, name: "IOTA", symbol: "MIOTA" },
    { id: 3794, name: "Cosmos", symbol: "ATOM" },
    { id: 1518, name: "Maker", symbol: "MKR" },
    { id: 2502, name: "Huobi Token", symbol: "HT" },
    { id: 7129, name: "TerraUSD", symbol: "UST" },
    { id: 3718, name: "BitTorrent", symbol: "BTT" },
    { id: 5034, name: "Kusama", symbol: "KSM" },
    { id: 5805, name: "Avalanche", symbol: "AVAX" },
    { id: 7186, name: "PancakeSwap", symbol: "CAKE" },
    { id: 4023, name: "Bitcoin BEP2", symbol: "BTCB" },
    { id: 4642, name: "Hedera Hashgraph", symbol: "HBAR" },
    { id: 4172, name: "Terra", symbol: "LUNA" },
    { id: 4157, name: "THORChain", symbol: "RUNE" },
    { id: 5692, name: "Compound", symbol: "COMP" },
    { id: 1274, name: "Waves", symbol: "WAVES" },
    { id: 3330, name: "Paxos Standard", symbol: "PAX" },
    { id: 131, name: "Dash", symbol: "DASH" },
    { id: 2700, name: "Celsius", symbol: "CEL" },
    { id: 873, name: "NEM", symbol: "XEM" },
    { id: 6892, name: "Elrond", symbol: "EGLD" },
    { id: 3822, name: "Theta Fuel", symbol: "TFUEL" },
    { id: 1437, name: "Zcash", symbol: "ZEC" },
    { id: 2586, name: "Synthetix", symbol: "SNX" },
    { id: 1168, name: "Decred", symbol: "DCR" },
    { id: 2563, name: "TrueUSD", symbol: "TUSD" },
    { id: 4066, name: "Chiliz", symbol: "CHZ" },
    { id: 5864, name: "yearn.finance", symbol: "YFI" },
    { id: 2135, name: "Revain", symbol: "REV" },
    { id: 4779, name: "HUSD", symbol: "HUSD" },
    { id: 6758, name: "SushiSwap", symbol: "SUSHI" },
    { id: 2394, name: "Telcoin", symbol: "TEL" },
    { id: 6535, name: "NEAR Protocol", symbol: "NEAR" },
    { id: 2682, name: "Holo", symbol: "HOT" },
    { id: 1966, name: "Decentraland", symbol: "MANA" },
    { id: 2469, name: "Zilliqa", symbol: "ZIL" },
    { id: 4847, name: "Stacks", symbol: "STX" },
    { id: 2083, name: "Bitcoin Gold", symbol: "BTG" },
    { id: 5665, name: "Helium", symbol: "HNT" },
    { id: 109, name: "DigiByte", symbol: "DGB" },
    { id: 1697, name: "Basic Attention Token", symbol: "BAT" },
    { id: 2694, name: "Nexo", symbol: "NEXO" },
    { id: 1698, name: "Horizen", symbol: "ZEN" },
    { id: 2566, name: "Ontology", symbol: "ONT" },
    { id: 6719, name: "The Graph", symbol: "GRT" },
    { id: 1684, name: "Qtum", symbol: "QTUM" },
    { id: 1567, name: "Nano", symbol: "NANO" },
    { id: 2130, name: "Enjin Coin", symbol: "ENJ" },
    { id: 1727, name: "Bancor", symbol: "BNT" },
    { id: 3897, name: "OKB", symbol: "OKB" },
    { id: 3945, name: "Harmony", symbol: "ONE" },
    { id: 1042, name: "Siacoin", symbol: "SC" },
    { id: 8335, name: "Mdex", symbol: "MDX" },
    { id: 3783, name: "Ankr", symbol: "ANKR" },
    { id: 5617, name: "UMA", symbol: "UMA" },
    { id: 1896, name: "0x", symbol: "ZRX" },
    { id: 2099, name: "ICON", symbol: "ICX" },
    { id: 5567, name: "Celo", symbol: "CELO" },
    { id: 1808, name: "OMG Network", symbol: "OMG" },
    { id: 2634, name: "XinFin Network", symbol: "XDC" },
    { id: 2577, name: "Ravencoin", symbol: "RVN" },
    { id: 3513, name: "Fantom", symbol: "FTM" },
    { id: 2499, name: "SwissBorg", symbol: "CHSB" },
    { id: 4558, name: "Flow", symbol: "FLOW" },
]